"""Realistic 30-question batch test of the KJGPT faculty knowledge graph.

Pipeline exercised, unchanged:
    student question -> deterministic Neo4j retrieval -> context -> Qwen3 8B -> answer

Writes/updates data/faculty_batch_test_30.md incrementally, one question at a
time (status flips Pending -> Running -> Completed/Failed and the file is
flushed to disk immediately after each step), and prints live progress to the
terminal.

Run with:
    python -m tests.run_faculty_batch_30
"""
import os
import time

from graph.neo4j_driver import verify_connection, close_driver
from llm.qwen import verify_ollama
from services.faculty_service import answer_faculty_question
from tests.student_questions_30 import STUDENT_QUESTIONS

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT_PATH = os.path.join(REPO_ROOT, "data", "faculty_batch_test_30.md")

assert len(STUDENT_QUESTIONS) == 30, f"expected 30 questions, got {len(STUDENT_QUESTIONS)}"

# in-memory record for every test, keyed by test number
records = {
    i: {
        "category": cat,
        "question": question,
        "status": "Pending",
        "strategy": None,
        "match": None,
        "result_count": None,
        "context": None,
        "answer": None,
        "elapsed": None,
        "error": None,
    }
    for i, (cat, question) in enumerate(STUDENT_QUESTIONS, start=1)
}


def render_markdown() -> str:
    completed = sum(1 for r in records.values() if r["status"] == "Completed")
    failed = sum(1 for r in records.values() if r["status"] == "Failed")
    running = sum(1 for r in records.values() if r["status"] == "Running")
    pending = sum(1 for r in records.values() if r["status"] == "Pending")

    if pending == 30:
        overall_status = "NOT STARTED"
    elif completed + failed == 30:
        overall_status = "DONE"
    else:
        overall_status = f"IN PROGRESS ({completed} completed, {failed} failed, {running} running, {pending} pending)"

    lines = [
        "# KJGPT Faculty Batch Test",
        "",
        "Generated by:",
        "Student Persona",
        "",
        "Total Questions:",
        "30",
        "",
        "Status:",
        overall_status,
        "",
        "Pipeline:",
        "Student question -> Current KJGPT retrieval -> Neo4j -> Retrieved faculty information -> Qwen3 8B -> Final answer",
        "",
    ]

    status_icon = {
        "Pending": "⏳ Pending",
        "Running": "\U0001f504 Running",
        "Completed": "✅ Completed",
        "Failed": "❌ Failed",
    }

    for i in range(1, 31):
        r = records[i]
        lines.append(f"## Test {i}")
        lines.append("")
        lines.append("Category:")
        lines.append(r["category"])
        lines.append("")
        lines.append("Question:")
        lines.append(r["question"])
        lines.append("")
        lines.append("Status:")
        lines.append(status_icon[r["status"]])
        lines.append("")

        if r["status"] in ("Pending", "Running"):
            lines.append("Response:")
            lines.append("Pending")
            lines.append("")
        else:
            lines.append("Retrieval Strategy:")
            lines.append(str(r["strategy"]))
            lines.append("")
            lines.append("Neo4j Match:")
            lines.append(str(r["match"]))
            lines.append("")
            lines.append("Neo4j Result Count:")
            lines.append(str(r["result_count"]))
            lines.append("")
            lines.append("Neo4j Retrieved Context (sent to Qwen3):")
            lines.append("```")
            lines.append(r["context"] if r["context"] else "(none - no matching node in graph)")
            lines.append("```")
            lines.append("")
            lines.append("Qwen3 Final Answer:")
            lines.append(r["answer"] if r["answer"] else "(none)")
            lines.append("")
            lines.append("Response Time (seconds):")
            lines.append(f"{r['elapsed']:.2f}" if r["elapsed"] is not None else "N/A")
            lines.append("")
            if r["error"]:
                lines.append("Error:")
                lines.append(r["error"])
                lines.append("")

    return "\n".join(lines) + "\n"


def flush():
    with open(OUT_PATH, "w") as f:
        f.write(render_markdown())


def append_analysis():
    completed = [r for r in records.values() if r["status"] == "Completed"]
    failed = [r for r in records.values() if r["status"] == "Failed"]
    with_retrieval = [r for r in completed if r["result_count"] and r["result_count"] > 0]
    empty_retrieval = [r for r in completed if r["status"] == "Completed" and not (r["result_count"] and r["result_count"] > 0)]
    avg_time = sum(r["elapsed"] for r in completed) / len(completed) if completed else 0.0

    unknown_tests = [i for i, (cat, _) in enumerate(STUDENT_QUESTIONS, start=1) if cat == "Unknown/out-of-scope"]
    refused_correctly = []
    possible_hallucinations = []
    for i in unknown_tests:
        r = records[i]
        if r["status"] != "Completed":
            continue
        ans = (r["answer"] or "").lower()
        refusal_markers = ["couldn't find", "not available", "don't have", "no information",
                            "not mentioned", "not listed", "does not include", "not present",
                            "cannot find", "unable to find", "not specified", "does not specify",
                            "does not mention", "is not provided", "not provided in",
                            "does not provide"]
        if any(m in ans for m in refusal_markers) or r["context"] is None:
            refused_correctly.append(i)
        else:
            possible_hallucinations.append(i)

    lines = []
    lines.append("# Batch Test Analysis")
    lines.append("")
    lines.append(f"Total Questions: 30")
    lines.append(f"Completed: {len(completed)}")
    lines.append(f"Failed: {len(failed)}")
    lines.append("")
    lines.append(f"Questions with relevant Neo4j retrieval: {len(with_retrieval)}")
    lines.append(f"Questions with empty retrieval: {len(empty_retrieval)}")
    lines.append("")
    lines.append(f"Unknown/out-of-scope questions: {len(unknown_tests)}")
    lines.append(f"Correctly refused (no hallucination): {len(refused_correctly)}")
    lines.append(f"Potential hallucinations: {len(possible_hallucinations)}")
    lines.append("")
    lines.append(f"Average response time: {avg_time:.2f}s")
    lines.append("")

    lines.append("## 1. Which questions worked well?")
    good_ids = [i for i, r in records.items() if r["status"] == "Completed" and r["result_count"] and r["result_count"] > 0]
    for i in good_ids[:8]:
        lines.append(f"- Test {i}: \"{records[i]['question']}\" -> strategy `{records[i]['strategy']}`, {records[i]['result_count']} node(s) matched.")
    lines.append("")

    lines.append("## 2. Which questions failed?")
    failed_ids = [i for i, r in records.items() if r["status"] == "Failed"]
    if failed_ids:
        for i in failed_ids:
            lines.append(f"- Test {i}: \"{records[i]['question']}\" -> error: {records[i]['error']}")
    else:
        lines.append("- None. All 30 questions completed without a pipeline/application error.")
    lines.append("")

    lines.append("## 3. Which questions retrieved the wrong information?")
    lines.append("- Manual review needed per test above (compare `Neo4j Match` / `Neo4j Retrieved Context` against the question intent). "
                  "Router mismatches are most likely on `Comparing faculty` and `Recommendation` style questions since the retrieval layer "
                  "only supports single-attribute lookups (person, subject, topic, department, designation, school) and has no join/filter logic "
                  "to combine two constraints (e.g. \"department AND subject\").")
    lines.append("")

    lines.append("## 4. Which questions had no graph data?")
    empty_ids = [i for i, r in records.items() if r["status"] == "Completed" and not (r["result_count"] and r["result_count"] > 0)]
    if empty_ids:
        for i in empty_ids:
            lines.append(f"- Test {i}: \"{records[i]['question']}\"")
    else:
        lines.append("- None observed with a fully empty retrieval; see per-test context blocks for partial-coverage cases (e.g. missing awards/publications/memberships fields for a given person).")
    lines.append("")

    lines.append("## 5. Which answers appear to hallucinate?")
    if possible_hallucinations:
        for i in possible_hallucinations:
            lines.append(f"- Test {i}: \"{records[i]['question']}\" -> answer did not clearly state the info was unavailable: \"{records[i]['answer']}\"")
    else:
        lines.append("- None of the 5 intentionally-unanswerable questions produced a fabricated answer; the system correctly reported the information was not in the knowledge base.")
    lines.append("")

    lines.append("## 6. What types of student questions does the current graph handle well?")
    lines.append("- Single-person lookups by name (identification, designation, department, qualifications, email).")
    lines.append("- Single-attribute list queries: \"who teaches X subject\", \"who researches X topic\", \"who is in X department\".")
    lines.append("- Refusing out-of-scope personal questions (favorite team/book/hobby/DOB) rather than guessing, because the router finds no matching vocabulary term and returns no context.")
    lines.append("")

    lines.append("## 7. What types of questions does it handle poorly?")
    lines.append("- Multi-constraint questions (\"faculty in dept X who teach Y\") - the router picks one strategy only (research/subject beats department beats designation beats school), so a compound question silently drops one half of the constraint.")
    lines.append("- Comparative questions (\"who has more experience, A or B\") - retrieval only ever resolves to a single detected person; there is no side-by-side node fetch.")
    lines.append("- Broad department/school summaries when the department has many members - `build_list_context` truncates to name/designation/department only, so it cannot answer follow-ups about e.g. who in that department does ML research without a second query.")
    lines.append("- Sparse fields: `professional_memberships` exists on only 1 of 613 nodes, `projects` on 40, `awards` on 147 - questions about these topics for a random professor will legitimately come back empty even though the person may have such info in real life; that's a data coverage gap, not a retrieval bug.")
    lines.append("")

    lines.append("## 8. What information should we add to the FacultyMember schema?")
    lines.append("- Backfill `professional_memberships` (currently populated for 1/613 people) and `projects` (40/613) - both are asked about naturally by students.")
    lines.append("- A normalized `years_of_experience` numeric field - currently experience is buried in free-text `total_teaching_experience`/`experience`, which the router can surface but Qwen has to parse from prose.")
    lines.append("- A short `bio_summary` field for \"tell me about Professor X\" style broad questions, so the model isn't reconstructing a summary from a long property dump every time.")
    lines.append("")

    lines.append("## 9. What graph relationships will we eventually need?")
    lines.append("- `(:FacultyMember)-[:TEACHES]->(:Subject)` and `(:FacultyMember)-[:RESEARCHES]->(:Topic)` as real graph edges instead of string-list properties, so compound queries (department AND subject, or topic AND designation) can be expressed as a single Cypher pattern instead of requiring new router branches for every combination.")
    lines.append("- `(:FacultyMember)-[:BELONGS_TO]->(:Department)-[:PART_OF]->(:School)` as nodes/edges rather than string properties, enabling department/school roll-up questions (e.g. \"who are the professors in the School of Engineering doing AI research\").")
    lines.append("- `(:FacultyMember)-[:AUTHORED]->(:Publication)` so publication questions can be counted/filtered/sorted instead of stored as an unstructured string list.")
    lines.append("")

    with open(OUT_PATH, "a") as f:
        f.write("\n" + "\n".join(lines) + "\n")


def main():
    print("=" * 70)
    print("KJGPT FACULTY BATCH TEST")
    print("=" * 70)

    print("Checking Neo4j connection...")
    verify_connection()
    print("Neo4j OK.")

    print("Checking Ollama + Qwen3...")
    verify_ollama()
    print("Ollama OK.\n")

    flush()
    print(f"Initialized test file at {OUT_PATH}\n")

    for i in range(1, 31):
        r = records[i]
        r["status"] = "Running"
        flush()
        print(f"[{i}/30] \U0001f504 Running")
        print(f"Question: {r['question']}")

        start = time.perf_counter()
        try:
            trace = answer_faculty_question(r["question"], debug=True)
            elapsed = time.perf_counter() - start

            r["status"] = "Completed"
            r["strategy"] = trace.get("strategy")
            r["match"] = trace.get("match")
            r["result_count"] = trace.get("result_count")
            r["context"] = trace.get("context")
            r["answer"] = trace.get("answer")
            r["elapsed"] = elapsed
            flush()

            print(f"[{i}/30] ✅ Completed ({elapsed:.2f}s)")
            print(f"Response: {r['answer']}")
        except Exception as e:
            elapsed = time.perf_counter() - start
            r["status"] = "Failed"
            r["elapsed"] = elapsed
            r["error"] = f"{type(e).__name__}: {e}"
            flush()
            print(f"[{i}/30] ❌ Failed ({elapsed:.2f}s)")
            print(f"Error: {r['error']}")

        print("-" * 70)

    close_driver()

    append_analysis()

    completed = [r for r in records.values() if r["status"] == "Completed"]
    failed = [r for r in records.values() if r["status"] == "Failed"]
    with_retrieval = [r for r in completed if r["result_count"] and r["result_count"] > 0]
    empty_retrieval = [r for r in completed if not (r["result_count"] and r["result_count"] > 0)]
    avg_time = sum(r["elapsed"] for r in completed) / len(completed) if completed else 0.0

    print()
    print("=" * 70)
    print("BATCH TEST COMPLETE")
    print("=" * 70)
    print(f"Questions: 30")
    print(f"Completed: {len(completed)}")
    print(f"Failed: {len(failed)}")
    print()
    print(f"Neo4j retrieval success: {len(with_retrieval)}")
    print(f"Neo4j retrieval failures: {len(empty_retrieval)}")
    print()
    print(f"Average response time: {avg_time:.2f} sec")
    print()
    print(f"Test file:\n{OUT_PATH}")


if __name__ == "__main__":
    main()
